### ISSUE TITLE
How to predict？

### ISSUE THREAD

**Issue by c464851257** [AutodeskAILab/UV-Net#15]
Thanks for sharing the code of UV-Net. I want to predict on segmentation model, but the code seems like not have predict function.

**Comment by pradeep-pyro** [comment]
Hi there, to get predictions from the segmentation model, you can call its `forward` method:
https://github.com/AutodeskAILab/UV-Net/blob/91cc97042ad56b5462fb36f21959c1963147d54d/uvnet/models.py#L295-L297)

The input is a batch of DGL graphs.

**Comment by c464851257** [comment]
> 

Thank you so much.

**Comment by pradeep-pyro** [comment]
Great, closing this issue.
