### ISSUE TITLE
AssertionError: Edge doesn't belong to face

### ISSUE THREAD

**Issue by Hurry-LJ** [AutodeskAILab/UV-Net#16]
Hi Autodesk AILab, thanks for UV-Net. When I generate the dataset (SolidLetters) using the script
`python -m process.solid_to_graph ~/h/data/SolidLetters/step ~/h/test/SolidLetters/train`
the issue appears.
Maybe this file: SolidLetters/step/d_Sail_upper.step

File "/anaconda3/envs/uv_net/lib/python3.9/site-packages/occwl/graph.py", line 43, in face_adjacency
    left_face, right_face = edge.find_left_and_right_faces(connected_faces)
  File "/anaconda3/envs/uv_net/lib/python3.9/site-packages/occwl/edge.py", line 442, in find_left_and_right_faces
    if face1.is_left_of(self):
  File "/anaconda3/envs/uv_net/lib/python3.9/site-packages/occwl/face.py", line 295, in is_left_of
    assert found_edge, "Edge doesn't belong to face"
AssertionError: Edge doesn't belong to face

**Comment by feilifan** [comment]
> Hi Autodesk AILab, thanks for UV-Net. When I generate the dataset (SolidLetters) using the script `python -m process.solid_to_graph ~/h/data/SolidLetters/step ~/h/test/SolidLetters/train` the issue appears. Maybe this file: SolidLetters/step/d_Sail_upper.step
> 
> File "/anaconda3/envs/uv_net/lib/python3.9/site-packages/occwl/graph.py", line 43, in face_adjacency left_face, right_face = edge.find_left_and_right_faces(connected_faces) File "/anaconda3/envs/uv_net/lib/python3.9/site-packages/occwl/edge.py", line 442, in find_left_and_right_faces if face1.is_left_of(self): File "/anaconda3/envs/uv_net/lib/python3.9/site-packages/occwl/face.py", line 295, in is_left_of assert found_edge, "Edge doesn't belong to face" AssertionError: Edge doesn't belong to face

 @Hurry-LJ  Hi,I noticed that a similar issue was raised here. Could you please share how it was resolved or provide guidance on handling this error?

**Comment by YannanXie** [comment]
@Hurry-LJ Hello, I also noticed that a similar issue was raised here. Could you please share how it was resolved or provide guidance on handling this error?

**Comment by feilifan** [comment]
这里是费立凡的邮箱，您的来信已收到，十分感谢
