### ISSUE TITLE
Using own STEP format data

### ISSUE THREAD

**Issue by A-CYNIC** [AutodeskAILab/UV-Net#8]
thanks for sharing the wonderful project.Now I want to process my own solid model data (in STEP format) into the .bin format that is understood by UV-Net,but i don't know how to do this.I see you haven't updated the guide yet,i will be appreciated  if you share the method about how to process step into the .bin format.

**Comment by pradeep-pyro** [comment]
Hi, I have the data processing pipeline in a separate branch here: https://github.com/AutodeskAILab/UV-Net/tree/process
The `process/solid_to_graph.py` is the script you need to process your own STEP files.

I haven't merged it into the `main` branch yet as I have to test it extensively on several experiments that we performed in the paper. If you're really interested in trying you can give it a shot right away.
